#!/usr/bin/env bash
#
# System tune in chroot
set -e

name="${1}"
password="${2}"

echo '- CHROOT'

# Tune the system
bsdtar --uid 0 --gid 0 -x -f /mnt/cfg.tar -C /

hwclock -w --utc

# Main
ln -sf /usr/share/zoneinfo/UTC /etc/localtime
useradd -m -G 'wheel,video' "${name}"
echo "${name}:${password}" | chpasswd
pacman -Scc --noconfirm

systemctl enable \
  systemd-networkd systemd-resolved systemd-networkd-persistent-storage \
  systemd-timesyncd fstrim.timer reflector.timer

systemctl mask systemd-networkd-wait-online

# systemd-boot
bootctl install --esp-path=/boot

echo '- Exiting chroot'
